// Generated file, do not manually edit. Generate from BE instead (php artisan app:generate-permission-constants)
export const Permissions = {
  VIEW_HORIZON_DASHBOARD: 'view_horizon_dashboard',
  VIEW_ADMIN_DASHBOARD: 'view_admin_dashboard',
  MANAGE_ADMINS: 'manage_admins',
  BROWSE_ADMINS: 'browse_admins',
  READ_ADMIN: 'read_admin',
  EDIT_ADMIN: 'edit_admin',
  ADD_ADMIN: 'add_admin',
  DELETE_ADMIN: 'delete_admin',
  MANAGE_USERS: 'manage_users',
  BROWSE_USERS: 'browse_users',
  READ_USER: 'read_user',
  EDIT_USER: 'edit_user',
  ADD_USER: 'add_user',
  DELETE_USER: 'delete_user',
  MANAGE_ATTENDANCES: 'manage_attendances',
  BROWSE_ATTENDANCES: 'browse_attendances',
  READ_ATTENDANCE: 'read_attendance',
  EDIT_ATTENDANCE: 'edit_attendance',
  ADD_ATTENDANCE: 'add_attendance',
  DELETE_ATTENDANCE: 'delete_attendance',
  MANAGE_USER_ATTENDANCES: 'manage_user_attendances',
  BROWSE_USER_ATTENDANCES: 'browse_user_attendances',
  READ_USER_ATTENDANCE: 'read_user_attendance',
  EDIT_USER_ATTENDANCE: 'edit_user_attendance',
  ADD_USER_ATTENDANCE: 'add_user_attendance',
  DELETE_USER_ATTENDANCE: 'delete_user_attendance',
};
